#!/bin/sh

# 以下の形式に入力された JSON を正規化
# {
#	name: {
#		name: {
#			name: value,
#			name: {
#				name: value }
#			,
#			name: {
#				name: value }
#		}  
#	}
# }  

# 入力行のクォートと改行を削除
tr -d '["\n]' |
# "{", "}", "," に改行を追加
sed -e 's/[{},]/&\n/g' |
#  パース処理
awk '
	# JSON フォーマットの : を削除
	function erase(str) {
		gsub(/:/, "", str)
		return str;
	}

	{
		# コンマを削除
		gsub(/,/, "");

		if($0 ~ /{/ && $1 != "{"){
			# name { の場合
			name[nest++] = erase($1);
		}
		else if(NF > 1){
			# "name: value" / "name: value }" の場合
			# 現在のネストまでの名前を出力
			for(i=0; i<nest; i++)
				printf "%s.", name[i];
			# 現在行の } 以外のフィールドを検出
			for(i=1; i<=NF; i++){
				if($i != "}"){
					w[i] = $i
					max = i
				}
				else
					nest--;
			}
			# name を出力
			for(j=1; j<max-1; j++)
				printf "%s.", erase(w[j])
			# ...name = value を出力
			printf "%s = \"%s\"\n", erase(w[max-1]), w[max]
		}
	}
'
